#Use the latest version of apache server image from docker hub
FROM httpd:latest

#Copy local index.html to the apache document root
COPY index.html /usr/local/apache2/htdocs/

#Expose port 80 to allow traffic
EXPOSE 80


