apiVersion: v1
kind: Pod
metadata:
  namespace: grafana
  name: grafana
  labels:
      app: grafana
spec: 
  containers:
  - name: grafana
    image: grafana/grafana:latest
    ports:
    - containerPort: 3000
    resources:
      limits:
        cpu: 100m
        memory: 240Mi
      requests:
        cpu: 50m
        memory: 120Mi
  nodeSelector:
    number: one