apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: grafana
spec:
  selector:
    web: nginx
  type: ClusterIP
  ports:
  - name: nginx
    protocol: TCP
    port: 8181
    targetPort: 80