apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-agent
spec:
  selector:
    matchLabels:
      app: monitor-nodes
  template:
    metadata:
      labels:
        app: monitor-nodes
    spec:
      containers:
      - name: 'nginx'
        image: nginx:latest